### ISSUE TITLE
not able to start tlbc-monitor after ctrl-c: UNIQUE constraint failed: blocks.hash

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/tlbc-monitor#1]
I've hit CTRL-C while syncing my node. Trying to start it again I get the following error, i.e. I'm not able to start it again:
```
~/trustlines/tlbc-monitor/t (git)-[master] % tlbc-monitor -c ~/trustlines/blockchain-next/config/trustlines-spec.json -u http://localhost:8545 -r reports 2>&1                 
2019-02-25 12:28.25 loading state                  path=PosixPath('/home/ralf/trustlines/tlbc-monitor/t/state/state')
2019-02-25 12:28.25 starting sync
Traceback (most recent call last):
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1210, in _execute_context
    cursor, statement, parameters, context
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 533, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: blocks.hash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ralf/trustlines/tlbc-monitor/monitor/db.py", line 64, in insert_branch
    session.commit()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1008, in commit
    self.transaction.commit()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 487, in commit
    self._prepare_impl()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 466, in _prepare_impl
    self.session.flush()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2424, in flush
    self._flush(objects)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2562, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2522, in _flush
    flush_context.execute()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1063, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
    distilled_params,
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1210, in _execute_context
    cursor, statement, parameters, context
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 533, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: blocks.hash [SQL: 'INSERT INTO blocks (hash, proposer, height) VALUES (?, ?, ?)'] [parameters: ((HexBytes('0x67f30e9ba904057b56004e50e50e0d4c698e5fe573dcf4094f98018351abd044'), b'1P\xffa\xdb\xe4Y\x15\x86\x15\xe5\x19%\rZ\x92\x02\x9d\x00\x8e', 45000), (HexBytes('0x4a163763cf2451dc72369f06180bfa403e73dac0c70e34841f62382098fe5590'), b'\x8dpn\xd4bH\xffN\x89ap\xa2\x9d9-i\xe4\xbf\x84\x04', 45001), (HexBytes('0x6f753ec61f07ac7218b82cb2acbf588c2fd353c1a752a996874963237a5029cc'), b'\xa6\xb6\xc7My\xc2\x10\xf8\xcd\xf3\x08\xa8\xf9\x1e*zYP\x96m', 45002), (HexBytes('0xae03d9f6bd536401b78dde71dff09f051b13a0ddd61c4be1d95f2e9dc87522ea'), b'\x87j\xc3%\x0f\xb8\xce\xben3\xb7\xdf\xa6O\xb2[\x18y_\x95', 45003), (HexBytes('0x236f0ec57030a29f553187e3b22aa652904297cac49c324fd4c02c5370d59775'), b'\xa2x\xceY\x85\x14A\xfa\xf4 pF\x8dq=\x13\x89\xda\x01\x83', 45004), (HexBytes('0x4b6424b77b4e60fe414361dbfee040764d15097abacbd9c5dd27d1ab497eb3a9'), b'L\x88\x88\n\xeem)\xa4\xcd\x0c?\xf7\xdf\x81:\x97C\xc1=\xb4', 45005), (HexBytes('0x980067d5c4da8b10e5c035152b8c724d52a21aed665ddfd58c271ebae8c46941'), b'\xc8\xfc\xe3l\xce\xd7\x02\x80\x92\x03\xc9\x12\x1e\xe6vz7g\x86\xcc', 45006), (HexBytes('0x74e1594e52839251f4e51ea57e132d730b26ee287d95e4e369325c3e80aa4c4d'), b"'\xe6\x92]\xd7\x8f\xab\xcc\x9d\x95\xda\x17\x8f\x9e\xbb\x98o\xa6o\xdb", 45007)  ... displaying 10 of 5000 total bound parameter sets ...  (HexBytes('0x6dd7e01f8d111f662fb7864649255f83a1183a6ee494146ca4e6c1d8f41b9193'), b'\xa9\x9c\x08\xb8E\xc0^\xe4r\x92\x8a\xe6l\x1b\x97\xee>M]\t', 49998), (HexBytes('0x9635186c1153e6dcc8e3161a5933df41363a3c642d9c0e2984c6a2fb27c16888'), b'1P\xffa\xdb\xe4Y\x15\x86\x15\xe5\x19%\rZ\x92\x02\x9d\x00\x8e', 49999))] (Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralf/trustlines/tlbc-monitor/monitor/block_fetcher.py", line 52, in _insert_branch
    self.db.insert_branch(blocks)
  File "/home/ralf/trustlines/tlbc-monitor/monitor/db.py", line 67, in insert_branch
    f"At least one block from the given branch already exists"
monitor.db.AlreadyExists: At least one block from the given branch already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralf/trustlines/venv/bin/tlbc-monitor", line 11, in <module>
    load_entry_point('tlbc-monitor', 'console_scripts', 'tlbc-monitor')()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ralf/trustlines/tlbc-monitor/monitor/main.py", line 303, in main
    loop.run_until_complete(app.run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/home/ralf/trustlines/tlbc-monitor/monitor/main.py", line 97, in run
    number_of_new_blocks = self.block_fetcher.fetch_and_insert_new_blocks()
  File "/home/ralf/trustlines/tlbc-monitor/monitor/block_fetcher.py", line 86, in fetch_and_insert_new_blocks
    number_of_synced_blocks += self._sync_forwards(max_forward_sync_blocks)
  File "/home/ralf/trustlines/tlbc-monitor/monitor/block_fetcher.py", line 118, in _sync_forwards
    self._insert_branch(blocks)
  File "/home/ralf/trustlines/tlbc-monitor/monitor/block_fetcher.py", line 54, in _insert_branch
    raise ValueError("Tried to insert already known block")
ValueError: Tried to insert already known block
tlbc-monitor -c ~/trustlines/blockchain-next/config/trustlines-spec.json -u    48.43s user 0.32s system 97% cpu 49.850 total
```

**Comment by schmir** [comment]
I've also got (after hitting ctrl backslash, which sends a QUIT signal):
```
~/trustlines/tlbc-monitor/t (git)-[master] % tlbc-monitor -c ~/trustlines/blockchain-next/config/trustlines-spec.json -u http://localhost:8545 -r reports 2>&1 |tee logfile.txt
2019-03-07 14:00.38 no state file found, starting from genesis
2019-03-07 14:00.38 starting sync
2019-03-07 14:01.29 received first block           step=308551073
2019-03-07 14:01.30 detected missed step           primary=0x876ac3250fb8cebe6e33b7dfa64fb25b18795f95 step=308551222
2019-03-07 14:01.30 detected missed step           primary=0xa278ce59851441faf42070468d713d1389da0183 step=308551223
2019-03-07 14:01.30 detected missed step           primary=0x4c88880aee6d29a4cd0c3ff7df813a9743c13db4 step=308551224
2019-03-07 14:01.31 detected missed step           primary=0xf7921f0bca54d81692656d357f88d51effd9e45a step=308551286
2019-03-07 14:01.31 detected missed step           primary=0x251968f7b5cd540814dc2b4e08634ae7fd59c9b1 step=308551288
2019-03-07 14:01.31 detected missed step           primary=0xe399d154168b8e9043589d4e8128d07f63c75d78 step=308551290
^C^\
[1]    18724 quit (core dumped)  tlbc-monitor -c ~/trustlines/blockchain-next/config/trustlines-spec.json -u   | 
       18725 interrupt           tee logfile.txt
tlbc-monitor -c ~/trustlines/blockchain-next/config/trustlines-spec.json -u    81.12s user 0.62s system 97% cpu 1:24.06 total
tee logfile.txt  0.00s user 0.00s system 0% cpu 1:21.11 total
130 ~/trustlines/tlbc-monitor/t (git)-[master] % tlbc-monitor -c ~/trustlines/blockchain-next/config/trustlines-spec.json -u http://localhost:8545 -r reports 2>&1 |tee logfile.txt
2019-03-07 14:02.05 no state file found, starting from genesis
2019-03-07 14:02.05 starting sync
Traceback (most recent call last):
  File "/home/ralf/trustlines/venv/bin/tlbc-monitor", line 11, in <module>
    load_entry_point('tlbc-monitor', 'console_scripts', 'tlbc-monitor')()
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ralf/trustlines/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ralf/trustlines/tlbc-monitor/monitor/main.py", line 303, in main
    loop.run_until_complete(app.run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/home/ralf/trustlines/tlbc-monitor/monitor/main.py", line 97, in run
    number_of_new_blocks = self.block_fetcher.fetch_and_insert_new_blocks()
  File "/home/ralf/trustlines/tlbc-monitor/monitor/block_fetcher.py", line 82, in fetch_and_insert_new_blocks
    self.fetch_forward_sync_target() - self.head.number,
AttributeError: 'NoneType' object has no attribute 'number'
```
