### ISSUE TITLE
AttributeError on reporting an equivocation

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/tlbc-monitor#25]
During the end2end tests of trustlines-network/project#405 for a real equivocation scenario, the following exception occurs after the monitoring service recognized such event and try to report it.
I want to note that the `main.py` module has never been tested before.

```sh
2019-04-25 14:08.15 detected equivocation          proposer=0x505ab22ef8f3ae874dec92e60665ca490fb68192 step=311238801
Traceback (most recent call last):
  File "./env/bin/tlbc-monitor", line 11, in <module>
    load_entry_point('tlbc-monitor', 'console_scripts', 'tlbc-monitor')()
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/main.py", line 405, in main
    app.run()
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/main.py", line 129, in run
    max_number_of_blocks=500
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 147, in fetch_and_insert_new_blocks
    number_of_synced_blocks += self._sync_backwards(max_backward_sync_blocks)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 178, in _sync_backwards
    self._insert_branch(list(reversed(self.current_branch)))
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 96, in _insert_branch
    self._run_callbacks(blocks)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 76, in _run_callbacks
    callback(block)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/equivocation_reporter.py", line 46, in __call__
    callback(block_hashes_by_same_proposer_on_same_step)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/main.py", line 278, in equivocation_logger
    "block_step": block_one.step,
AttributeError: 'AttributeDict' object has no attribute 'step'
```

**Comment by weilbith** [comment]
The error is easy to fix and has been already locally confirmed. It is only about a quick design decision with @jannikluhn left before opening the PR.

**Comment by jannikluhn** [comment]
It's probably gonna be easier to discuss the design decision once you've opened the PR.
