### ISSUE TITLE
Run manual end2end test for new monitor

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/tlbc-monitor#47]
To not have the automated end2end tests a blocker we should run a manual test now.
This should at least include switching from a validator set as a list with one offline validator to the same validator set in a contract with one offline validator and then see if the transition works fine and the validator is reported before and after the fork.

**Comment by weilbith** [comment]
Test on 13429503ede5c8c38848653fac9331b1bda8250f

```python
Traceback (most recent call last):
  File "monitor/main.py", line 441, in <module>
    main()
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "monitor/main.py", line 437, in main
    app.run()
  File "monitor/main.py", line 137, in run
    self._run_cycle()
  File "monitor/main.py", line 146, in _run_cycle
    max_block_height=self.epoch_fetcher.last_fetch_height,
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 164, in fetch_and_insert_new_blocks
    max_block_height=max_block_height,
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 203, in _sync_backwards
    self._insert_branch(list(reversed(self.current_branch)))
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 99, in _insert_branch
    self._run_callbacks(blocks)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/block_fetcher.py", line 79, in _run_callbacks
    callback(block)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/skip_reporter.py", line 83, in __call__
    callback(primary, proposal)
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/offline_reporter.py", line 94, in __call__
    if self._is_offline(primary):
  File "/home/thore/brainbot/projects/trustlines-network/equivocation_e2e_test/tlbc-monitor/monitor/offline_reporter.py", line 144, in _is_offline
    skip_rate = self.offline_time_by_validator[validator] / self.offline_window_size
ZeroDivisionError: division by zero
```

I'll checkout why this is the case.

**Comment by weilbith** [comment]
# Conclusion

The monitor do not report offline validators after switching to a validator set
contract.

# Configuration

## Parity

- use version `v2.4.6`

## Monitor

- use commit 13429503ede5c8c38848653fac9331b1bda8250f (`HEAD@master` at this point)
- set `--offline-window` to `15s`

## Chain Specification

- `stepDuration` of 5(s)
- three validator addresses from block `0` in a static list
- three addresses from block `15` in a contract (pre-calculated deploy address)
- all validators are registered as bootstrap nodes

# Setup

- start validator `1` and `2` while `3` remains offline from the beginning
- start a plain node for the monitor to synchronize
- deployment of the `ValidatorSet` contract within the first three blocks
- start monitor connected to the plain node

# Process

(after deployment and start of monitor)

- monitor synchronize up to 100%
- monitor detects missed step at block #9 by `3`rd validator
- monitor reports offline validator at block #9 for validator `3`
- monitor continuously detect missing steps
- all Parity nodes log the signaled validator set transition and apply it after
  block `15`
- monitor continue to synchronize and detect missed steps, but do not report
  the offline validator anymore
- stopped test at block #28

# Report Directory Content

`skips`:

```
311739890,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:04:10
311739893,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:04:25
311739896,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:04:40
311739899,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:04:55
311739902,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:05:10
311739905,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:05:25
311739908,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:05:40
311739911,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:05:55
311739914,0x7b946c0390ce3649eadde84dbab538f084734a23,2019-05-24 12:06:10
```

`offline_report_0x7b946c0390ce3649eadde84dbab538f084734a23_steps_311739890_to_311739890`:

```
{"validator": "0x7b946c0390ce3649eadde84dbab538f084734a23", "missed_steps": [311739890]}
```

**Comment by weilbith** [comment]
@berndbohmeier @jannikluhn please checkout the results.

**Comment by weilbith** [comment]
On request I can send you all log files by the Parity clients and the monitor.

**Comment by jannikluhn** [comment]
If I understand correctly (not sure I do), then this is intended behavior. There's one offline validator which is reported once. They should not be reported again, even if the validator set changes.

**Comment by weilbith** [comment]
> and the validator is reported before and after the fork.

Sry, I related to this...

**Comment by berndbohmeier** [comment]
This is intended behavior as long as the skips are still reported.

**Comment by jannikluhn** [comment]
Looks like they do, so I'm happy

**Comment by berndbohmeier** [comment]
if you want to try if the offline report works also over the fork, you could set the offline window bigger than the fork time. 
So for example fork at 30 sec, ratio 0.5, offline window 2 min should result in the validator being reported at 1 min, so 30 sec after the fork.

**Comment by berndbohmeier** [comment]
@weilbith ^

**Comment by weilbith** [comment]
Should I do a second run with the `3`rd validator up in the beginning until the contract is applied and then turn off?

**Comment by weilbith** [comment]
Or like this. Maybe both. :thinking:

**Comment by berndbohmeier** [comment]
Try either, how you want.

**Comment by jannikluhn** [comment]
if you do a second run, you could also just have validators 1 and 2 in the list, and only add 3 in the fork.

**Comment by weilbith** [comment]
Sry for the delay. I can confirm that both scenarios work as well. Looks like a success to me. :+1:

**Comment by berndbohmeier** [comment]
Thanks, good job!
