### ISSUE TITLE
Monitor crash with ZeroDivisionError on empty chain

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/tlbc-monitor#51]
This error has been observed when starting a new chain with a fresh _Parity_ and immediately connect the monitor to this node. This result into the problem that the node can be connected already via the RPC interface, but no block is available in the chain. As result the following stack trace will be logged:

```sh
2019-05-27 13:41.58 no state entry found, starting from fresh state
2019-05-27 13:41.58 starting sync
2019-05-27 13:41.58 starting initial sync from Block(0, 1970-01-01T00:00:00+00:00), latest Block(0, 1970-01-01T00:00:00+00:00)
2019-05-27 13:41.58 no new blocks                  head_hash=HexBytes('0x0623358dade3bfdd7cfd2052104a11a5bfd14754e2b7cc8457d39d93566b41a2') head_number=0
Traceback (most recent call last):
  File "/usr/local/bin/tlbc-monitor", line 10, in <module>
    sys.exit(main())
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/monitor/main.py", line 376, in main
    app.run()
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/monitor/main.py", line 118, in run
    self._run_cycle()
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/monitor/main.py", line 133, in _run_cycle
    f"Syncing ({(int(self.block_fetcher.get_sync_status_percentage()))}%) "
  File "/opt/tlbc-monitor/lib/python3.6/site-packages/monitor/block_fetcher.py", line 227, in get_sync_status_percentage
    return head_block_number / last_block_number * 100
ZeroDivisionError: division by zero
```

An error message which is more related to the actual issue should be considered here.

**Comment by berndbohmeier** [comment]
Please make sure that you run the newest version. 
The should be fixed already. Reopen if you still see this issue with the newest version.
